platform :ios, '12.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Adicionando suporte a M1 Macs e arquitetura ARM64 para simuladores
$RNFirebaseAsStaticFramework = true

target 'app' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    :fabric_enabled => config[:fabricEnabled],
    :codegen_disabled => false
  )

  pod 'Firebase/Core', :modular_headers => true

  target 'appTests' do
    inherit! :complete
    # Pods for testing
  end

  # Configurações pós-instalação do React Native
  post_install do |installer|
    # Ajustando a meta de implantação para todos os Pods
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end

    # Excluindo arquiteturas não suportadas para simuladores
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end

    # Adicionando a equipe de desenvolvimento para assinatura de código
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['DEVELOPMENT_TEAM'] = '375WVRSY2Q'
      end
    end

    # Aplique a configuração também ao alvo principal do app
    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.user_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['DEVELOPMENT_TEAM'] = '375WVRSY2Q'
        end
      end
    end

    # React Native Post Install
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
